# Generated by Django 5.2.8 on 2025-11-22 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyseCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fichier', models.CharField(help_text='Ex: etl_ventes.py', max_length=255, verbose_name='Nom du fichier')),
                ('outil', models.CharField(choices=[('SQL', 'SQL'), ('Python', 'Python'), ('DAX', 'DAX (Power BI)'), ('PowerQuery', 'Power Query (M)')], default='Python', max_length=20, verbose_name='Langage/Outil')),
                ('contenu_code', models.TextField(help_text='Le code à analyser', verbose_name='Code source')),
                ('description', models.TextField(blank=True, help_text='Que fait ce code?', verbose_name='Description')),
                ('score', models.IntegerField(default=0, help_text='Score de 0 à 100', verbose_name='Score de qualité')),
                ('est_approuve', models.BooleanField(default=False, verbose_name='Approuvé pour production')),
                ('temps_analyse', models.FloatField(default=0.0, verbose_name="Temps d'analyse (secondes)")),
                ('nb_problemes_total', models.IntegerField(default=0)),
                ('nb_critiques', models.IntegerField(default=0)),
                ('nb_warnings', models.IntegerField(default=0)),
                ('nb_infos', models.IntegerField(default=0)),
                ('nb_flake8', models.IntegerField(default=0)),
                ('nb_bandit', models.IntegerField(default=0)),
                ('nb_openai', models.IntegerField(default=0)),
                ('nb_manuel', models.IntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name="Date d'analyse")),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Analysé par')),
            ],
            options={
                'verbose_name': 'Analyse de code',
                'verbose_name_plural': 'Analyses de code',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Probleme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severite', models.CharField(choices=[('critique', 'Critique'), ('warning', 'Warning'), ('info', 'Info')], default='info', max_length=20)),
                ('categorie', models.CharField(choices=[('performance', 'Performance'), ('securite', 'Sécurité'), ('qualite', 'Qualité des données'), ('lisibilite', 'Lisibilité'), ('style', 'Style (PEP8)'), ('complexite', 'Complexité')], default='lisibilite', max_length=20)),
                ('source', models.CharField(choices=[('manuel', 'Règles manuelles'), ('flake8', 'Flake8'), ('bandit', 'Bandit'), ('openai', 'OpenAI')], default='manuel', max_length=20)),
                ('message', models.TextField(verbose_name="Message d'erreur")),
                ('suggestion', models.TextField(blank=True, verbose_name='Suggestion de correction')),
                ('ligne', models.IntegerField(blank=True, null=True, verbose_name='Numéro de ligne')),
                ('colonne', models.IntegerField(blank=True, null=True, verbose_name='Numéro de colonne')),
                ('code_erreur', models.CharField(blank=True, help_text='Ex: E501, B105', max_length=20, verbose_name='Code erreur')),
                ('analyse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problemes', to='core.analysecode', verbose_name='Analyse')),
            ],
            options={
                'verbose_name': 'Problème',
                'verbose_name_plural': 'Problèmes',
                'ordering': ['severite', 'ligne'],
            },
        ),
    ]
